version: "3"

services:
  shortitpy-api:
    container_name: shortitpy-api
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - 80:80
    volumes:
      - .:/usr/src/shortitpy
    depends_on:
      - shortitpy-redis
    networks:
      - redis-network

  shortitpy-redis:
    container_name: shortitpy-redis
    image: redis:latest
    ports:
      - "${REDIS_PORT}:6379"

    networks:
      - redis-network
    environment:
      - REDIS_PASSWORD:${REDIS_PASSWORD}
    command: >
      --requirepass ${REDIS_PASSWORD}

networks:
  redis-network: {}
