version: "3"

services:
  shortitpy-api:
    container_name: shortitpy-api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 80:80
    depends_on:
      - shortitpy-redis

    environment:
      - REDIS_NETWORK_NAME=${REDIS_NETWORK_NAME}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_DB=${REDIS_DB}
      - REDIRECTION_BASE_URL=${REDIRECTION_BASE_URL}
      - SHORT_URL_TTL=${SHORT_URL_TTL}

    networks:
      - redis-network

  shortitpy-redis:
    container_name: shortitpy-redis
    image: redis:latest
    ports:
      - "${REDIS_PORT}:6379"
    networks:
      - redis-network
    environment:
      - REDIS_PASSWORD:${REDIS_PASSWORD}
    command: >
      --requirepass ${REDIS_PASSWORD}

networks:
  redis-network: {}
