version: 2.1

jobs:
  build:
    working_directory: ~/project
    docker:
      - image: docker:17.05.0-ce-git

    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: false

      - run:
          name: Installing dependencies
          command: |
            apk add --no-cache py-pip
            pip install docker-compose

      - run:
          name: Gathering .env file data
          command: |
            echo REDIS_NETWORK_NAME=${REDIS_NETWORK_NAME} >> .env
            echo REDIS_PASSWORD=${REDIS_PASSWORD} >> .env
            echo REDIS_PORT=${REDIS_PORT} >> .env
            echo REDIS_DB=${REDIS_DB} >> .env
            echo REDIRECTION_BASE_URL=${REDIRECTION_BASE_URL} >> .env
            echo SHORT_URL_TTL=${SHORT_URL_TTL} >> .env

      - run:
          name: Running tests
          command: |
            docker-compose up -d
            docker exec -it api pytest shortitpy-api
            docker exec -it api pytest shortitpy-api --integration
            docker-compose down
