version: 2.1

base_config: &base_config
  working_directory: ~/project
  docker:
    - image: cimg/base:2022.08

jobs:
  build:
    <<: *base_config

    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true # should not be important
          version: 20.10.12

      - run:
          name: Installing dependencies...
          command: |
            sudo apt-get update && sudo apt-get install python3-pip

      - run:
          name: Gathering .env file data
          command: |
            echo REDIS_NETWORK_NAME=${REDIS_NETWORK_NAME} >> .env
            echo REDIS_PASSWORD=${REDIS_PASSWORD} >> .env
            echo REDIS_PORT=${REDIS_PORT} >> .env
            echo REDIS_DB=${REDIS_DB} >> .env
            echo REDIRECTION_BASE_URL=${REDIRECTION_BASE_URL} >> .env
            echo SHORT_URL_TTL=${SHORT_URL_TTL} >> .env

      - run:
          name: Running tests...
          command: |
            docker compose -f docker-compose.dev.yml run shortitpy-api ls > log.txt
            cat log.txt
            docker compose -f docker-compose.dev.yml run shortitpy-api pytest shortitpy
            docker compose -f docker-compose.dev.yml run shortitpy-api pytest shortitpy --integration
            docker-compose -f docker-compose.dev.yml down

      # Store shortitpy files for the next job
      # - persist_to_workspace:
      #     root: ~/project
      #     paths:
      #       - ./

  # tests:
  #   <<: *base_config

  #   steps:
  #     # Start with the initial build
  #     - attach_workspace:
  #         at: ~/project

  #     - run:
  #         name: Gathering .env file data
  #         command: |
  #           echo REDIS_NETWORK_NAME=${REDIS_NETWORK_NAME} >> .env
  #           echo REDIS_PASSWORD=${REDIS_PASSWORD} >> .env
  #           echo REDIS_PORT=${REDIS_PORT} >> .env
  #           echo REDIS_DB=${REDIS_DB} >> .env
  #           echo REDIRECTION_BASE_URL=${REDIRECTION_BASE_URL} >> .env
  #           echo SHORT_URL_TTL=${SHORT_URL_TTL} >> .env

  #     - run:
  #         name: Running tests...
  #         command: |
  #           sudo dockerd
  #           docker-compose -f docker-compose.dev.yml up -d
  #           docker-compose -f docker-compose.dev.yml run shortitpy-api pytest shortitpy
  #           docker-compose -f docker-compose.dev.yml run shortitpy-api pytest shortitpy --integration
  #           docker-compose -f docker-compose.dev.yml down

workflows:
  full:
    jobs:
      - build
